apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: neopro

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml

configMapGenerator:
  - name: central-server-config
    behavior: merge
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - ALLOWED_ORIGINS=https://dashboard.neopro.fr

images:
  - name: ghcr.io/neopro/central-server
    newTag: latest
