apiVersion: v1
kind: Service
metadata:
  name: central-server
  namespace: neopro
  labels:
    app: central-server
    app.kubernetes.io/name: central-server
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app: central-server
---
apiVersion: v1
kind: Service
metadata:
  name: central-server-headless
  namespace: neopro
  labels:
    app: central-server
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: http
      port: 3001
      targetPort: http
  selector:
    app: central-server
