apiVersion: v1
kind: ServiceAccount
metadata:
  name: central-server
  namespace: neopro
  labels:
    app: central-server
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: central-server
  namespace: neopro
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: central-server
  namespace: neopro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: central-server
subjects:
  - kind: ServiceAccount
    name: central-server
    namespace: neopro
