apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: central-server
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://staging.dashboard.neopro.fr"
spec:
  tls:
    - hosts:
        - staging.api.neopro.fr
      secretName: staging-central-server-tls
  rules:
    - host: staging.api.neopro.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: central-server
                port:
                  name: http
